# Generated by Django 4.0.5 on 2022-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livro_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ISNB',
            new_name='isbn',
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
